# Generated by Django 5.0.6 on 2024-12-13 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudades',
            fields=[
                ('id_ciu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='modelos',
            fields=[
                ('id_mod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mod', models.CharField(max_length=100)),
                ('color_mod', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('id_vehi', models.AutoField(primary_key=True, serialize=False)),
                ('fabricacion_vehi', models.IntegerField()),
                ('precio_vehi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('placa_vehi', models.CharField(max_length=100)),
                ('fk_id_mod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Mecanico.modelos')),
            ],
        ),
        migrations.CreateModel(
            name='propietarios',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=100)),
                ('apellido_pro', models.CharField(max_length=100)),
                ('email_pro', models.EmailField(max_length=250)),
                ('telefono_pro', models.CharField(max_length=100)),
                ('fk_id_ciu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Mecanico.ciudades')),
                ('fk_id_vehi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Mecanico.vehiculos')),
            ],
        ),
    ]
